{
 "title": "Assets",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Total bruto",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(sumSeries(seriesByTag('risk=~low|high')), 0.001)"
    }
   ]
  },
  {
   "title": "Patrimônio em risco",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(#A, #D)",
     "targetFull": "divideSeries(sumSeries(seriesByTag('risk=high')), sumSeries(sumSeries(seriesByTag('risk=high')), sumSeries(seriesByTag('risk=low'))))"
    }
   ]
  },
  {
   "title": "Renda variável",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "countSeries(seriesByTag('risk=high', 'kind!=wallet', 'lifecycle=yielding'))"
    }
   ]
  },
  {
   "title": "Renda fixa",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "countSeries(seriesByTag('risk=low', 'kind!=wallet', 'lifecycle=yielding'))"
    }
   ]
  },
  {
   "title": "Contas principais",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(mine.jpmorgan.*, 'JP Morgan CC')"
    },
    {
     "target": "alias(mine.sumitomo, 'Sumitomo')"
    },
    {
     "target": "alias(sumSeries(mine.citigroup.rf.*), 'Citigroup RF')"
    },
    {
     "target": "alias(sumSeries(mine.citigroup.rv.*), 'Citigroup RV')"
    },
    {
     "target": "alias(mine.citigroup.citigroup_cc, 'Citigroup CC')"
    }
   ]
  },
  {
   "title": "Renda fixa",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "target": "cdi/yielding", "type": "table" }
   ]
  },
  {
   "title": "Alto risco",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(seriesByTag('risk=high')), '(.*?);.*', '\\1')"
    }
   ]
  }
 ]
}