{
 "title": "Tracker",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Moedas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "aliasByMetric(currency.*)" }
   ]
  },
  {
   "title": "Fundos",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "aliasByMetric(fundo.*)" }
   ]
  },
  {
   "title": "Ações",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "aliasByNode(stock.*, 1)" }
   ]
  }
 ]
}