#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
source "${ROOT}/scripts/core.sh"

warning "Start building image..."

cd "$ROOT"
hash=$(git rev-parse --short HEAD)
docker build --tag 'denisidoro/rosebud:latest' --tag "denisidoro/rosebud:$hash" .

success "Image builded!"
